version: "3.8"

x-base-app-test: &base-app-test
  image: dynamiq-app:${IMAGE_TAG:-local}
  build:
    target: develop
  volumes:
    - ./:/app

x-app-test: &app-test
  <<: *base-app-test
  entrypoint: ["make", "test"]
  env_file:
    - .env

services:
  dynamiq-app:
    <<: *base-app-test

  dynamiq-app-test:
    <<: *app-test

  dynamiq-app-test-cov:
    <<: *app-test
    entrypoint: ["make", "test-cov"]
    volumes:
      - ./reports:/app/reports:wr
